services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_eureka_service
    build:
      context: ./
    networks:
      - dev_net
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "8761:8761"
networks:
  dev_net:
    name: ${COMPOSE_PROJECT_NAME}_network

