services:
  eurekaapplicationservice:
    container_name: ${COMPOSE_PROJECT_NAME}_eureka_service
    build:
      context: ./
    networks:
      - dev_net
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "127.0.0.1:8761:8761"
networks:
  dev_net:
    name: ${COMPOSE_PROJECT_NAME}_network

